### ISSUE TITLE
Support for Django 2.0

### ISSUE THREAD

**Issue by rafaelwinter** [Kemaweyan/django-content-gallery#3]
I installed django-content-gallery using pip, but got an exception when executing it's migration.

`python manage.py migrate content_gallery` throws the following exception:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/content_gallery/models.py", line 8, in <module>
    from . import utils
  File "/home/winter/.virtualenvs/devenv/lib/python3.6/site-packages/content_gallery/utils.py", line 8, in <module>
    from django.core import urlresolvers
ImportError: cannot import name 'urlresolvers'
```

**Comment by yggi** [comment]
Seconded.

The migration seems to work when changing the import from django.core.urlresovers to django.urls.

But afterwards, jquery in the admin interface is broken.

I did not dig further, for now I stay with django 1.11

**Comment by claguerre** [comment]
The migration seems to work when changing the import from django.core.urlresovers to django.urls.
Rise  error when clic on add image in admin.

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/content_gallery/image/add/?_to_field=id&_popup=1&object_id=8&content_type=18
2.1.2
TypeError
render() got an unexpected keyword argument 'renderer'
C:\wamp64\www-src\venv\lib\site-packages\django\forms\boundfield.py in as_widget, line 93
